name: Terraform Scalingo Provision

on:
  push:
    branches:
      - main  

jobs:
  terraform:
    name: Terraform Provision
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: .

      - name: Plan Terraform
        run: terraform plan -var="scalingo_token=${{ secrets.SCALINGO_TOKEN }}"
        working-directory: .

      - name: Apply Terraform
        run: terraform apply -auto-approve -var="scalingo_token=${{ secrets.SCALINGO_TOKEN }}"
        working-directory: .
        env:
          SCALINGO_TOKEN: ${{ secrets.SCALINGO_TOKEN }}
