name: Terraform Scalingo Provision

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Scalingo Terraform Provider (compatible GitHub Actions)
        run: |
          mkdir -p ~/.terraform.d/plugins/registry.scalingo.com/scalingo/scalingo/0.3.0/linux_amd64
          curl -L -o ~/.terraform.d/plugins/registry.scalingo.com/scalingo/scalingo/0.3.0/linux_amd64/terraform-provider-scalingo \
            https://github.com/kolok/terraform-provider-scalingo/releases/download/v0.3.0-fixed/terraform-provider-scalingo_0.3.0_linux_amd64
          chmod +x ~/.terraform.d/plugins/registry.scalingo.com/scalingo/scalingo/0.3.0/linux_amd64/terraform-provider-scalingo


      - name: Affiche le contenu du dossier infra
        run: |
          echo "Contenu de infra/"
          ls -l infra
          echo "--- main.tf ---"
          cat infra/main.tf

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Plan Terraform (avec -var)
        run: terraform plan -input=false -no-color -var="scalingo_token=${{ secrets.SCALINGO_TOKEN }}"
        working-directory: infra

      - name: Apply Terraform (avec -var)
        run: terraform apply -auto-approve -var="scalingo_token=${{ secrets.SCALINGO_TOKEN }}"
        working-directory: infra
