name: Terraform Scalingo Provision

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Download Scalingo Terraform Provider
        run: |
          mkdir -p ~/.terraform.d/plugins/registry.scalingo.com/scalingo/scalingo/0.3.0/linux_amd64
          curl -L -o ~/.terraform.d/plugins/registry.scalingo.com/scalingo/scalingo/0.3.0/linux_amd64/terraform-provider-scalingo \
            https://github.com/Scalingo/terraform-provider-scalingo/releases/download/v0.3.0/terraform-provider-scalingo_0.3.0_linux_amd64
          chmod +x ~/.terraform.d/plugins/registry.scalingo.com/scalingo/scalingo/0.3.0/linux_amd64/terraform-provider-scalingo

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Plan Terraform
        run: terraform plan
        working-directory: infra

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: infra
        env:
          SCALINGO_TOKEN: ${{ secrets.SCALINGO_TOKEN }}
