name: Terraform Scalingo Provision

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Plan Terraform
        run: terraform plan -input=false -no-color -var="scalingo_token=${{ secrets.SCALINGO_TOKEN }}"
        working-directory: infra

      - name: Apply Terraform
        run: terraform apply -auto-approve -var="scalingo_token=${{ secrets.SCALINGO_TOKEN }}"
        working-directory: infra
