name: Terraform scalingo provision

on:
  push:
    branches:
      - prod

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Plan Terraform
        run: terraform plan
        working-directory: infra

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: infra
        env:
          SCALINGO_TOKEN: ${{ secrets.SCALINGO_TOKEN }}
